### ISSUE TITLE
add contact form

### ISSUE THREAD

**Issue by JKHeadley** [cusac/mbt.guide#23]
We need a contact form for volunteers or anyone interested (or anyone with questions) so that we don't have to give out emails.

Ideally this would be protected from bots with re-captcha or the like.

**Comment by oormicreations** [comment]
Added a contact form. It is a google form, so that admins can change it without changing the code. 
Only problem, it still shows the default video on top. We need conditional routes. (At present I do not know how to do that)

**Comment by oormicreations** [comment]
Removed default video (or last viewed).
It is working, but not in an ideal way. Still needs conditional routes with search box.
