### ISSUE TITLE
Last time stamp time into new one.

### ISSUE THREAD

**Issue by xmarkurion** [cusac/mbt.guide#41]
After you create a timestamp when you want to add the next one.
The time of the beginning of the new timestamp should be the same as the ending time of the timestamp before it.
And the duration should be increased to the end of the video.

My idea to avoid null state is this:

if( "there is **non** of any timestamp")
{
   1st timestamp after creates button will start from beginning to the half of the video. ( !important) 
   
    if (end of timestamp before == end of the video time) { die } 
    else 
   {
      Load the beginning time from the ending of timestamp before to the freshly created one.
      Extend the end time of the new segment to the ( time of the video - 1minute ) 
   }
} else die.

So the code activates only if there is non of any timestamp created for this video.
Also, it will stop working until user adds a timestamp that ends at the end of the video.

**Comment by oormicreations** [comment]
Closing.
