### ISSUE TITLE
As a <user> I want <a landing page> so that <I can get oriented>.

### ISSUE THREAD

**Issue by JKHeadley** [cusac/mbt.guide#70]
The app needs an actual home/landing page where users orient themselves and can easily find what they are looking for. As usual, look to youtube for an example. The home page should still have an option to start searching segments.

**Comment by oormicreations** [comment]
We can add a new landing page for guest users. Logged in users will see volunteer landing page (as it is now).
But do you want everyone to be able to log in? If yes, the above will fail. And we will need a way to separate logged in user from a logged in volunteer.
Another way is to have a common landing page with two sections. 
Please let me know your thoughts about it.

**Comment by JKHeadley** [comment]
Good points!

My thoughts are that in general we should always assume users (logged in or not) are general users, not volunteers, as they will (hopefully) be the majority of users on the site. Yes, we will definitely want all users to be able to log in so they can customize profiles, create playlists, etc.

My thoughts are that volunteers will receive instructions during onboarding on how to indicate in their profile that they are a volunteer after logging in. This could be a simple checkmark on their profile page. Checking this option will customize the landing page, initial segment times, etc.

Of course there are several missing features (such as a user profile page) that will be needed to support this functionality. I don't see this as too high of a priority right now since we have much to do in general. So for now we can continue with the assumption that all users are volunteers.

However it would be beneficial to start thinking through the different features that will be required to support the "custom profile" option and start creating new issues /epics to represent these.

**Comment by oormicreations** [comment]
Sure, we will discuss it later in more detail. I guess there is already a field in the DB that marks a user as volunteer or admin etc. If yes, that can be used to set a landing page.

**Comment by JKHeadley** [comment]
Yes, we can add a "Volunteer" group and check if users belong to that group. This can be done in the admin app: 

https://mbt-guide-admin.netlify.app/groups

**Comment by oormicreations** [comment]
I tried that , the create group button is disabled. Probably you can add it, but not so urgent.

**Comment by oormicreations** [comment]
Volunteer group is created.
Still getting undefined.
